import Footer from "../layouts/Footer"
import { Helmet } from "react-helmet-async";


const PrivacyPolicy = () => {
    return (
        <>
            <Helmet>
                <title>SkrillBot | Privacy Policy</title>
                <meta name="description" content=" Skrillbot's Privacy Policy | Your Personal Information is Secure with Us - Learn How We Protect Your Data" />
                <meta rel="canonical" href="/privacy-policy" />
            </Helmet>
            <section className="container md:mt-24 px-12 text-justify">
                <h2 className="md:text-4xl text-2xl my-4">Privacy Policy <span className="font-light">- Privacy Policy for Skrillbot</span></h2>
                <h3 className="md:text-2xl text-xl font-light mb-4">Effective Date: 2023-03-11</h3>
                <p className="mb-4 text-md">Skrillbot values your privacy and is committed to protecting your personal information. This Privacy Policy describes how Skrillbot collects, uses, and shares the personal information you provide to us when you access and use our services. By using Skrillbot's services, you agree to the collection and use of your personal information as outlined in this Privacy Policy.
                </p>
                <h4 className="text-indigo-500 text-lg font-bold">Information We Collect</h4>
                <p className="mb-4 text-md">We collect various types of personal information from you, including:</p>
                <ul className="ml-4 list-disc">
                    <li className="mb-4 text-md">Contact Information: We collect your name, email address, and phone number when you register for Skrillbot's services.</li>
                    <li className="mb-4 text-md">Payment Information: We collect your credit card information when you purchase Skrillbot's services.</li>
                    <li className="mb-4 text-md">Writing and Coding Information: We collect information related to the writing and coding services you request, including the content you provide, the results generated by Skrillbot, and your feedback.</li>
                    <li className="mb-4 text-md">Usage Information: We collect information about how you use Skrillbot's services, including your IP address, browser type, and device type.</li>
                </ul>
                <h4 className="text-indigo-500 text-lg font-bold">How We Use Your Information</h4>
                <p className="mb-4 text-md">We use your personal information for the following purposes:</p>
                <ul className="ml-4 list-disc">
                    <li className="mb-4 text-md">To provide and improve our services;</li>
                    <li className="mb-4 text-md">To process your payments and transactions;</li>
                    <li className="mb-4 text-md">To communicate with you about our services and promotions;</li>
                    <li className="mb-4 text-md">To respond to your inquiries and requests;</li>
                    <li className="mb-4 text-md">To analyze and improve the quality of our services;</li>
                    <li className="mb-4 text-md">To comply with our legal and regulatory obligations.</li>
                </ul>
                <h4 className="text-indigo-500 text-lg font-bold">How We Share Your Information</h4>
                <p className="mb-4 text-md">We may share your personal information with the following parties:</p>
                <ul className="ml-4 list-disc">
                    <li className="mb-4 text-md">Service Providers: We may share your personal information with third-party service providers who assist us in providing and improving our services, such as payment processors, hosting providers, and customer support providers.</li>
                    <li className="mb-4 text-md">Business Partners: We may share your personal information with our business partners who assist us in promoting our services, such as marketing and advertising partners.</li>
                    <li className="mb-4 text-md">Legal and Regulatory Authorities: We may share your personal information as required by law or regulation, or to comply with legal processes or government requests.</li>
                    <li className="mb-4 text-md">Merger or Acquisition: We may share your personal information in connection with a merger, acquisition, or sale of all or a portion of our business or assets.</li>
                </ul>
                <h4 className="text-indigo-500 text-lg font-bold">Cookies and Other Tracking Technologies</h4>
                <p className="mb-4 text-md">We use cookies and other tracking technologies to enhance your user experience and improve our services. A cookie is a small text file that is stored on your device when you visit a website. We use cookies to remember your preferences, analyze how you use our services, and personalize your experience. You can disable cookies in your browser settings, but please note that some features of our services may not function properly if cookies are disabled.</p>
                <h4 className="text-indigo-500 text-lg font-bold">Data Security</h4>
                <p className="mb-4 text-md">We take reasonable measures to protect your personal information from unauthorized access, disclosure, alteration, and destruction. However, no data transmission over the internet or any wireless network can be guaranteed to be 100% secure. Therefore, we cannot guarantee the security of your personal information.</p>
                <h4 className="text-indigo-500 text-lg font-bold">Children's Privacy</h4>
                <p className="mb-4 text-md">Skrillbot's services are not intended for use by children under the age of 13. We do not knowingly collect personal information from children under the age of 13. If we become aware that we have collected personal information from a child under the age of 13, we will take steps to delete the information as soon as possible.</p>
                {/* 
                <ul className="ml-4 list-disc">
                    <li className="mb-4 text-md"></li>
                    <li className="mb-4 text-md"></li>
                    <li className="mb-4 text-md"></li>
                </ul>
             */}
                <h4 className="text-indigo-500 text-lg font-bold">Changes to this Privacy Policy</h4>
                <p className="mb-4 text-md">We may update this Privacy Policy from time to time by posting a new version on our website. Your continued use of Skrillbot's services after any changes to this Privacy Policy constitutes your acceptance of the revised Privacy Policy</p>
                <h4 className="text-indigo-500 text-lg font-bold">Your Choices</h4>
                <p className="mb-4 text-md">You can access and update your personal information by logging into your Skrillbot account. You may also request that we delete your personal information by contacting us at skrillbotai@gmail.com. Please note that we may retain certain information as required by law or for legitimate business purposes.</p>
                <h4 className="text-indigo-500 text-lg font-bold">Contact Us</h4>
                <p className="mb-4 text-md">If you have any questions or concerns about this Privacy Policy or Skrillbot's privacy practices, please contact us at skrillbotai@gmail.com.</p>
                <h4 className="text-indigo-500 text-lg font-bold">Governing Law</h4>
                <p className="mb-4 text-md">This Privacy Policy is governed by and construed in accordance with the laws of the jurisdiction where Skrillbot is based, without giving effect to any principles of conflicts of law. Any dispute arising out of or related to this Privacy Policy shall be resolved exclusively in the state or federal courts located in the jurisdiction where Skrillbot is based.</p>
                <h4 className="text-indigo-500 text-lg font-bold">Use of Services</h4>
                <p className="mb-4 text-md">By using Skrillbot's services, you agree to the terms and conditions outlined in this Privacy Policy. If you do not agree to the terms and conditions outlined in this policy, please do not use Skrillbot's services.</p>
                <Footer />
            </section>
        </>
    )
}
export default PrivacyPolicy