import Footer from "../layouts/Footer"

const TermsOfUse = () => {
    return (
        <section className="container md:mt-24 px-12 text-justify">
            <h2 className="md:text-4xl text-2xl my-4">Terms of use <span className="font-light">- Terms of Use Policy for Skrillbot</span></h2>
            <h3 className="md:text-2xl text-xl font-light mb-4">Effective Date: 2023-03-11</h3>
            <p className="mb-4 text-md">
                Welcome to Skrillbot! Skrillbot is an AI-powered company that provides various writing services, including essay writing, blog article writing, ad copywriting, homework help, and coding generators. By accessing and using Skrillbot's services, you agree to comply with the terms and conditions outlined in this Terms of Use Policy.
            </p>
            <h4 className="text-indigo-500 text-lg font-bold">Use of Services</h4>
            <p className="mb-4 text-md">Skrillbot provides writing and coding services to assist users in generating content. You agree to use Skrillbot's services only for lawful purposes and in compliance with all applicable laws, rules, and regulations. You are solely responsible for ensuring that your use of Skrillbot's services complies with all applicable laws and regulations.</p>
            <h4 className="text-indigo-500 text-lg font-bold">Ownership of Content</h4>
            <p className="mb-4 text-md">All content generated by Skrillbot, including essays, blog articles, ad copies, homework help, and coding generators, are the property of Skrillbot. Skrillbot grants you a non-exclusive, non-transferable, limited license to use the content generated by Skrillbot for personal, non-commercial purposes only. Skrillbot retains all rights, title, and interest in and to the content generated by Skrillbot.</p>
            <h4 className="text-indigo-500 text-lg font-bold">Commercial Use</h4>
            <p className="mb-4 text-md">You are allowed to use any content generated by Skrillbot commercially, subject to the following conditions:</p>
            <ul className="ml-4 list-disc">
                <li className="mb-4 text-md">You must obtain Skrillbot's prior written consent before using the content generated by Skrillbot commercially.</li>
                <li className="mb-4 text-md">You must attribute the content generated by Skrillbot to Skrillbot.</li>
                <li className="mb-4 text-md">You must comply with all applicable laws, rules, and regulations</li>
            </ul>
            <h4 className="text-indigo-500 text-lg font-bold">Intellectual Property</h4>
            <p className="mb-4 text-md">Skrillbot and its licensors own all intellectual property rights in and to the services, including all content, software, technology, and other materials used or made available by Skrillbot. You agree not to copy, modify, distribute, sell, or otherwise exploit any of Skrillbot's intellectual property rights without Skrillbot's prior written consent.</p>
            <h4 className="text-indigo-500 text-lg font-bold">Disclaimer of Warranties</h4>
            <p className="mb-4 text-md">Skrillbot provides its services "as is" and without any warranty or condition, express, implied, or statutory. Skrillbot does not warrant that its services will be uninterrupted, error-free, or free of harmful components. Skrillbot does not warrant that the results obtained from the use of its services will be accurate or reliable.</p>
            <h4 className="text-indigo-500 text-lg font-bold">Use of Services</h4>
            <p className="mb-4 text-md"></p>
            <h4 className="text-indigo-500 text-lg font-bold">Limitation of Liability</h4>
            <p className="mb-4 text-md">Skrillbot shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses, resulting from:</p>
            <ul className="ml-4 list-disc">
                <li className="mb-4 text-md">your access to or use of Skrillbot's services;</li>
                <li className="mb-4 text-md"> any conduct or content of any third party on Skrillbot's services;</li>
                <li className="mb-4 text-md">any content generated by Skrillbot;</li>
                <li className="mb-4 text-md">any unauthorized access, use, or alteration of your transmissions or content;</li>
                <li className="mb-4 text-md">any other matter relating to Skrillbot's services.</li>
            </ul>
            <h4 className="text-indigo-500 text-lg font-bold">Governing Law and Jurisdiction</h4>
            <p className="mb-4 text-md">This Terms of Use Policy shall be governed by and construed in accordance with the laws of [Jurisdiction]. Any disputes arising under or in connection with this Terms of Use Policy shall be subject to the exclusive jurisdiction of the courts located in [Jurisdiction].
            </p>
            <p className="mb-4 text-md">If you have any questions or concerns about this Terms of Use Policy, please contact Skrillbot at skrillbotai@gmail.com.</p>
            <h4 className="text-indigo-500 text-lg font-bold">Modifications to Terms of Use</h4>
            <p className="mb-4 text-md">Skrillbot reserves the right to modify or update this Terms of Use Policy at any time without prior notice. Your continued use of Skrillbot's services following any such modification or update constitutes your acceptance of the revised Terms of Use Policy.</p>
            <h4 className="text-indigo-500 text-lg font-bold">Termination</h4>
            <p className="mb-4 text-md">Skrillbot may terminate or suspend your access to all or any part of its services at any time, with or without cause, with or without notice, effective immediately. If you wish to terminate this agreement, you may discontinue using Skrillbot's services.</p>
            <h4 className="text-indigo-500 text-lg font-bold">Entire Agreement</h4>
            <p className="mb-4 text-md">This Terms of Use Policy constitutes the entire agreement between you and Skrillbot regarding the use of its services and supersedes all prior or contemporaneous communications and proposals, whether oral or written, between you and Skrillbot.</p>
            <p className="mb-4 text-md">By using Skrillbot's services, you agree to be bound by this Terms of Use Policy. If you do not agree to the terms and conditions outlined in this policy, please do not use Skrillbot's services.</p>
            <Footer />
        </section>
    )
}
export default TermsOfUse